require 'yaml'

data = YAML.load_file('external/FFXIVClientStructs/ida/data.yml')
globals = data['globals']
    .to_a
    .map { |addr, var| "constexpr size_t #{var.gsub("::", "_").gsub("g_", "")} = 0x#{(addr - 0x140000000).to_s(16)};" }
    .join("\n")

functions = data['functions']
    .to_a
    .map { |addr, var| "constexpr size_t #{var.gsub("Client::", "").gsub("::", "_")} = 0x#{(addr - 0x140000000).to_s(16)};" }
    .join("\n")

output = %{// This file is autogenerated by scripts/generate_addresses.rb
#pragma once
#include <cstdint>

// Relative to base address
namespace game::offsets::globals {
#{globals}
}

namespace game::offsets::functions {
#{functions}
}
}

IO.write('CoreNative/src/game/Addresses.h', output)